RocketBoards/Controllers/BuildBoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RocketBoards.Models;

namespace RocketBoards.Controllers
{
    public class BuildBoardsController : Controller
    {
        private readonly RocketBoardsContext _context;

        public BuildBoardsController(RocketBoardsContext context)
        {
            _context = context;
        }

        // GET: BuildBoards
        public async Task<IActionResult> Index()
        {
            var rocketBoardsContext = _context.BuildBoard.Include(b => b.Block).Include(b => b.Fin).Include(b => b.ModelBoard);
            return View(await rocketBoardsContext.ToListAsync());
        }

        // GET: BuildBoards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildBoard = await _context.BuildBoard
                .Include(b => b.Block)
                .Include(b => b.Fin)
                .Include(b => b.ModelBoard)
                .FirstOrDefaultAsync(m => m.BuildBoardId == id);
            if (buildBoard == null)
            {
                return NotFound();
            }

            return View(buildBoard);
        }

        // GET: BuildBoards/Create
        public IActionResult Create()
        {
            ViewData["BlockId"] = new SelectList(_context.Block, "BlockId", "Material");
            ViewData["FinId"] = new SelectList(_context.Fin, "FinId", "Material");
            ViewData["ModelBoardId"] = new SelectList(_context.ModelBoard, "ModelBoardId", "Model");
            return View();
        }

        // POST: BuildBoards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BuildBoardId,BlockId,FinId,ModelBoardId")] BuildBoard buildBoard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(buildBoard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BlockId"] = new SelectList(_context.Block, "BlockId", "Material", buildBoard.BlockId);
            ViewData["FinId"] = new SelectList(_context.Fin, "FinId", "Material", buildBoard.FinId);
            ViewData["ModelBoardId"] = new SelectList(_context.ModelBoard, "ModelBoardId", "Model", buildBoard.ModelBoardId);
            return View(buildBoard);
        }

        // GET: BuildBoards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildBoard = await _context.BuildBoard.FindAsync(id);
            if (buildBoard == null)
            {
                return NotFound();
            }
            ViewData["BlockId"] = new SelectList(_context.Block, "BlockId", "Material", buildBoard.BlockId);
            ViewData["FinId"] = new SelectList(_context.Fin, "FinId", "Material", buildBoard.FinId);
            ViewData["ModelBoardId"] = new SelectList(_context.ModelBoard, "ModelBoardId", "Model", buildBoard.ModelBoardId);
            return View(buildBoard);
        }

        // POST: BuildBoards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BuildBoardId,BlockId,FinId,ModelBoardId")] BuildBoard buildBoard)
        {
            if (id != buildBoard.BuildBoardId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buildBoard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuildBoardExists(buildBoard.BuildBoardId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BlockId"] = new SelectList(_context.Block, "BlockId", "Material", buildBoard.BlockId);
            ViewData["FinId"] = new SelectList(_context.Fin, "FinId", "Material", buildBoard.FinId);
            ViewData["ModelBoardId"] = new SelectList(_context.ModelBoard, "ModelBoardId", "Model", buildBoard.ModelBoardId);
            return View(buildBoard);
        }

        // GET: BuildBoards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildBoard = await _context.BuildBoard
                .Include(b => b.Block)
                .Include(b => b.Fin)
                .Include(b => b.ModelBoard)
                .FirstOrDefaultAsync(m => m.BuildBoardId == id);
            if (buildBoard == null)
            {
                return NotFound();
            }

            return View(buildBoard);
        }

        // POST: BuildBoards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buildBoard = await _context.BuildBoard.FindAsync(id);
            _context.BuildBoard.Remove(buildBoard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BuildBoardExists(int id)
        {
            return _context.BuildBoard.Any(e => e.BuildBoardId == id);
        }
    }
}

RocketBoards/Controllers/RegistersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RocketBoards.Models;

namespace RocketBoards.Controllers
{
    public class RegistersController : Controller
    {
        private readonly RocketBoardsContext _context;

        public RegistersController(RocketBoardsContext context)
        {
            _context = context;
        }

        // GET: Registers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Register.ToListAsync());
        }

        // GET: Registers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var register = await _context.Register
                .FirstOrDefaultAsync(m => m.RegisterId == id);
            if (register == null)
            {
                return NotFound();
            }

            return View(register);
        }

        // GET: Registers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Registers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RegisterId")] Register register)
        {
            if (ModelState.IsValid)
            {
                _context.Add(register);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(register);
        }

        // GET: Registers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var register = await _context.Register.FindAsync(id);
            if (register == null)
            {
                return NotFound();
            }
            return View(register);
        }

        // POST: Registers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RegisterId")] Register register)
        {
            if (id != register.RegisterId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(register);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegisterExists(register.RegisterId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(register);
        }

        // GET: Registers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var register = await _context.Register
                .FirstOrDefaultAsync(m => m.RegisterId == id);
            if (register == null)
            {
                return NotFound();
            }

            return View(register);
        }

        // POST: Registers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var register = await _context.Register.FindAsync(id);
            _context.Register.Remove(register);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegisterExists(int id)
        {
            return _context.Register.Any(e => e.RegisterId == id);
        }
    }
}

RocketBoards/Controllers/ShapersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RocketBoards.Models;

namespace RocketBoards.Controllers
{
    public class ShapersController : Controller
    {
        private readonly RocketBoardsContext _context;

        public ShapersController(RocketBoardsContext context)
        {
            _context = context;
        }

        // GET: Shapers
        public async Task<IActionResult> Index()
        {
            var rocketBoardsContext = _context.Shaper.Include(s => s.Brand);
            return View(await rocketBoardsContext.ToListAsync());
        }

        // GET: Shapers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shaper = await _context.Shaper
                .Include(s => s.Brand)
                .FirstOrDefaultAsync(m => m.ShaperId == id);
            if (shaper == null)
            {
                return NotFound();
            }

            return View(shaper);
        }

        // GET: Shapers/Create
        public IActionResult Create()
        {
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name");
            return View();
        }

        // POST: Shapers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShaperId,Name,BrandId")] Shaper shaper)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shaper);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name", shaper.BrandId);
            return View(shaper);
        }

        // GET: Shapers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shaper = await _context.Shaper.FindAsync(id);
            if (shaper == null)
            {
                return NotFound();
            }
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name", shaper.BrandId);
            return View(shaper);
        }

        // POST: Shapers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShaperId,Name,BrandId")] Shaper shaper)
        {
            if (id != shaper.ShaperId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shaper);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShaperExists(shaper.ShaperId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name", shaper.BrandId);
            return View(shaper);
        }

        // GET: Shapers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shaper = await _context.Shaper
                .Include(s => s.Brand)
                .FirstOrDefaultAsync(m => m.ShaperId == id);
            if (shaper == null)
            {
                return NotFound();
            }

            return View(shaper);
        }

        // POST: Shapers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shaper = await _context.Shaper.FindAsync(id);
            _context.Shaper.Remove(shaper);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShaperExists(int id)
        {
            return _context.Shaper.Any(e => e.ShaperId == id);
        }
    }
}

RocketBoards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RocketBoards</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div id="header">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="surf/images/logo.png" alt="" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pranchas <i class="fas fa-angle-down"></i></a>
                            <div class="dropdown-menu">
                                <a asp-area="" asp-controller="BuildBoards" asp-action="Create" class="dropdown-item">Montar Prancha</a>
                                <a asp-area="" asp-controller="Shapers" class="dropdown-item">Shapers Disponíveis</a>
                            </div>
                            <!-- end .dropdown-menu -->
                        </li>
                        <li class="nav-item active">
                            <a asp-area="" asp-controller="Registers" asp-action="Index" class="nav-link">Gerenciar</a>
                        </li>
                    </ul>
                    <!-- end .navbar-nav -->
                </div>
                <!-- end .collapse -->
            </div>
            <!-- end .container -->
        </nav>
        <!-- end .navbar -->

    </div>
    <!-- end #header -->
    </header>
    <!-- end #header-wrap -->
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - RocketBoards - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

RocketBoards/Views/Shared/_LayoutSurf.cshtml
<!doctype html>
<html lang="zxx">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="icon" href="surf/images/favicon.ico">
    <title>@ViewData["Title"] - DreamBoards</title>

    <!-- Web Fonts
    ================================================== -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="surf/css/bootstrap.css">
    <link rel="stylesheet" href="surf/fonts/css/fontawesome-all.css">
    <link rel="stylesheet" href="surf/css/plugins.css">
    <link rel="stylesheet" href="surf/css/style.css">

    <div id="boxed-wrap">
        <header id="header-wrap">

            <!-- Header
            ================================================== -->
            <div id="header">
                <nav class="navbar navbar-expand-lg">
                    <div class="container">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                            <img src="surf/images/logo.png" alt="" />
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse justify-content-end" id="navbarNavDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pranchas <i class="fas fa-angle-down"></i></a>
                                    <div class="dropdown-menu">
                                        <a asp-area="" asp-controller="BuildBoards" asp-action="Create" class="dropdown-item">Montar Prancha</a>
                                        <a asp-area="" asp-controller="BuildBoards" asp-action="Index" class="dropdown-item">Pranchas Prontas</a>
                                        <a asp-area="" asp-controller="Shapers" asp-action="Index" class="dropdown-item">Shapers Disponíveis</a>
                                    </div>
                                    <!-- end .dropdown-menu -->
                                </li>
                                <li class="nav-item active">
                                    <a asp-area="" asp-controller="Registers" class="nav-link">Gerenciar</a>
                                </li>
                            </ul>
                            <!-- end .navbar-nav -->
                        </div>
                        <!-- end .collapse -->
                    </div>
                    <!-- end .container -->
                </nav>
                <!-- end .navbar -->

            </div>
            <!-- end #header -->
        </header>
        <!-- end #header-wrap -->
</head>
<body>
    @RenderBody()

    <!-- Footer
    ================================================== -->
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <h4>About Us</h4>
                    <div class="titleline-footer">
                    </div>
                    <!-- end .titleline-footer -->
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
                </div>
                <!-- end .col-lg-3 -->

                <div class="col-lg-3">
                    <h4>Support</h4>
                    <div class="titleline-footer">
                    </div>
                    <!-- end .titleline-footer -->
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
                </div>
                <!-- end .col-lg-3 -->

                <div class="col-lg-3">
                    <h4>Company</h4>
                    <div class="titleline-footer">
                    </div>
                    <!-- end .titleline-footer -->
                    <ul class="footer-list">
                        <li>
                            <i class="fas fa-angle-right"></i>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                        <li>
                            <i class="fas fa-angle-right"></i>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                    </ul>
                </div>
                <!-- end .col-lg-3 -->

                <div class="col-lg-3">
                    <h4>Contact Us</h4>
                    <div class="titleline-footer">
                    </div>
                    <!-- end .titleline-footer -->
                    <ul class="footer-list">
                        <li>
                            <i class="fas fa-angle-right"></i>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                        <li>
                            <i class="fas fa-angle-right"></i>
                            <a href="#">Lorem ipsum dolor sit amet</a>
                        </li>
                    </ul>
                </div>
                <!-- end .col-lg-3 -->

            </div>
            <!-- end .row -->
        </div>
        <!-- end .container -->
    </footer>
    <!-- end #footer -->
    <!-- Copyright
    ================================================== -->
    <div id="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="copyright r-divider justify-content-start">
                        <li>
                            <a href="#">Lorem ipsum</a>
                        </li>
                        <li>
                            <a href="#">Lorem ipsum</a>
                        </li>
                        <li>
                            <a href="#">Lorem ipsum</a>
                        </li>
                    </ul>
                </div>
                <!-- end .col-lg-6 -->

                <div class="col-lg-6">
                    <ul class="copyright justify-content-end">
                        <li>
                            &copy; 2018 <a href="#">DreamBoards</a> All Rights Reserved.
                        </li>
                       
                    </ul>
                </div>
                <!-- end .col-lg-6 -->

            </div>
            <!-- end .row -->
        </div>
        <!-- end .container -->
    </div>
    <!-- end #copyright -->
    </div>
    <!-- end #boxed-wrap -->

    <div id="back-to-top">
        <a href="#">Back to Top</a>
    </div>

    <!-- end #back-to-top -->
    <!-- Java Script
    ================================================== -->
    @RenderSection("Scripts", required: false)
    <script src="surf/js/jquery.min.js"></script>
    <script src="surf/js/popper.min.js"></script>
    <script src="surf/js/bootstrap.min.js"></script>
    <script src="surf/js/plugins.js"></script>
    <script src="surf/js/custom.js"></script>
</body>
</html>