RocketBoards/Models/Register.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RocketBoards.Models
{
    public class Register
    {

        public int RegisterId { get; set; }
    }
}

RocketBoards/Controllers/BlocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RocketBoards.Models;

namespace RocketBoards.Controllers
{
    public class BlocksController : Controller
    {
        private readonly RocketBoardsContext _context;

        public BlocksController(RocketBoardsContext context)
        {
            _context = context;
        }

        // GET: Blocks
        public async Task<IActionResult> Index()
        {
            var rocketBoardsContext = _context.Block.Include(b => b.Shaper);
            return View(await rocketBoardsContext.ToListAsync());
        }

        // GET: Blocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var block = await _context.Block
                .Include(b => b.Shaper)
                .FirstOrDefaultAsync(m => m.BlockId == id);
            if (block == null)
            {
                return NotFound();
            }

            return View(block);
        }

        // GET: Blocks/Create
        public IActionResult Create()
        {
            ViewData["ShaperId"] = new SelectList(_context.Shaper, "ShaperId", "Name");
            return View();
        }

        // POST: Blocks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlockId,Material,Stringer,Height,Width,Boarder,ShaperId")] Block block)
        {
            if (ModelState.IsValid)
            {
                _context.Add(block);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShaperId"] = new SelectList(_context.Shaper, "ShaperId", "Name", block.ShaperId);
            return View(block);
        }

        // GET: Blocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var block = await _context.Block.FindAsync(id);
            if (block == null)
            {
                return NotFound();
            }
            ViewData["ShaperId"] = new SelectList(_context.Shaper, "ShaperId", "Name", block.ShaperId);
            return View(block);
        }

        // POST: Blocks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BlockId,Material,Stringer,Height,Width,Boarder,ShaperId")] Block block)
        {
            if (id != block.BlockId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(block);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlockExists(block.BlockId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShaperId"] = new SelectList(_context.Shaper, "ShaperId", "Name", block.ShaperId);
            return View(block);
        }

        // GET: Blocks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var block = await _context.Block
                .Include(b => b.Shaper)
                .FirstOrDefaultAsync(m => m.BlockId == id);
            if (block == null)
            {
                return NotFound();
            }

            return View(block);
        }

        // POST: Blocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var block = await _context.Block.FindAsync(id);
            _context.Block.Remove(block);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlockExists(int id)
        {
            return _context.Block.Any(e => e.BlockId == id);
        }
    }
}

RocketBoards/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RocketBoards.Models;

namespace RocketBoards.Controllers
{
    public class BrandsController : Controller
    {
        private readonly RocketBoardsContext _context;

        public BrandsController(RocketBoardsContext context)
        {
            _context = context;
        }

        // GET: Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brand.ToListAsync());
        }

        // GET: Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BrandId,Name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BrandId,Name")] Brand brand)
        {
            if (id != brand.BrandId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.BrandId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brand
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brand.FindAsync(id);
            _context.Brand.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brand.Any(e => e.BrandId == id);
        }
    }
}

RocketBoards/Controllers/FinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RocketBoards.Models;

namespace RocketBoards.Controllers
{
    public class FinsController : Controller
    {
        private readonly RocketBoardsContext _context;

        public FinsController(RocketBoardsContext context)
        {
            _context = context;
        }

        // GET: Fins
        public async Task<IActionResult> Index()
        {
            var rocketBoardsContext = _context.Fin.Include(f => f.Brand);
            return View(await rocketBoardsContext.ToListAsync());
        }

        // GET: Fins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fin = await _context.Fin
                .Include(f => f.Brand)
                .FirstOrDefaultAsync(m => m.FinId == id);
            if (fin == null)
            {
                return NotFound();
            }

            return View(fin);
        }

        // GET: Fins/Create
        public IActionResult Create()
        {
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name");
            return View();
        }

        // POST: Fins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FinId,BrandId,Material,Model")] Fin fin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name", fin.BrandId);
            return View(fin);
        }

        // GET: Fins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fin = await _context.Fin.FindAsync(id);
            if (fin == null)
            {
                return NotFound();
            }
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name", fin.BrandId);
            return View(fin);
        }

        // POST: Fins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FinId,BrandId,Material,Model")] Fin fin)
        {
            if (id != fin.FinId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FinExists(fin.FinId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brand, "BrandId", "Name", fin.BrandId);
            return View(fin);
        }

        // GET: Fins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fin = await _context.Fin
                .Include(f => f.Brand)
                .FirstOrDefaultAsync(m => m.FinId == id);
            if (fin == null)
            {
                return NotFound();
            }

            return View(fin);
        }

        // POST: Fins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fin = await _context.Fin.FindAsync(id);
            _context.Fin.Remove(fin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FinExists(int id)
        {
            return _context.Fin.Any(e => e.FinId == id);
        }
    }
}

RocketBoards/Views/Registers/Create.cshtml
@model RocketBoards.Models.Register

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Register</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RocketBoards/Views/Registers/Delete.cshtml
@model RocketBoards.Models.Register

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Register</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RegisterId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RocketBoards/Views/Registers/Details.cshtml
@model RocketBoards.Models.Register

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Register</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RegisterId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RocketBoards/Views/Registers/Edit.cshtml
@model RocketBoards.Models.Register

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Register</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RegisterId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RocketBoards/Views/Registers/Index.cshtml
@model IEnumerable<RocketBoards.Models.Register>

@{
    ViewData["Title"] = "Gerenciar";
    Layout = "~/Views/Shared/_LayoutSurf.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <a asp-area="" asp-controller="Brands" asp-action="Index" class="nav-link">
                <h5>Marcas</h5>

                <a class="nivo-lightbox" href="~/surf/images/card/marcas.jpg" title="Image Title">
                    <img class="image-align-left" src="~/surf/images/card/marcas.jpg" alt="" />
                </a>
                <p><span class="dropcap">G</span> erencie todas as marcas, cadastrando e pesquisando.</p>
            </a>
        </div>
        <!-- end .col-lg-6 -->
        <div class="col-lg-6">
            <a asp-area="" asp-controller="Shapers" asp-action="Index" class="nav-link">
                <h3>Shapers</h3>
                <a class="nivo-lightbox" href="~/surf/images/card/shaper.jpg" title="Image Title">
                    <img class="image-align-right" src="~/surf/images/card/shaper.jpg" alt="" />
                </a>
                <p><span class="dropcap">G</span> erencie todas os Shapers, cadastrando e pesquisando.</p>
            </a>
        </div>
        <!-- end .col-lg-6 -->

    </div>
    <!-- end .row -->
</div>
<!-- end .container -->
<div class="mb-100">
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <a asp-area="" asp-controller="Blocks" asp-action="Index" class="nav-link">
                <h3>Bloco</h3>
                <a class="nivo-lightbox" href="~/surf/images/card/bloco.jpg" title="Image Title">
                    <img class="image-align-left" src="~/surf/images/card/bloco.jpg" alt="" />
                </a>
                <p><span class="dropcap">G</span> erencie todas os blocos, cadastrando e pesquisando.</p>
            </a>
        </div>
        <!-- end .col-lg-6 -->
        <div class="col-lg-6">
            <a asp-area="" asp-controller="Fins" asp-action="Index" class="nav-link">
                <h3>Quilhas</h3>
                <a class="nivo-lightbox" href="~/surf/images/card/quilhas.jpg" title="Image Title">
                    <img class="image-align-right" src="~/surf/images/card/quilhas.jpg" alt="" />
                </a>
                <p><span class="dropcap">G</span> erencie todas as quilhas, cadastrando e pesquisando.</p>
            </a>
        </div>
        <!-- end .col-lg-6 -->

    </div>
    <!-- end .row -->
</div>
<!-- end .container -->
<div class="mb-100">
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <a asp-area="" asp-controller="ModelBoards" asp-action="Index" class="nav-link">
                <h3>Modelo da Prancha</h3>
                <a class="nivo-lightbox" href="~/surf/images/card/modelos.png" title="Image Title">
                    <img class="image-align-left" src="~/surf/images/card/modelos.png" alt="" />
                </a>
                <p><span class="dropcap">G</span> erencie todas os modelos, cadastrando e pesquisando.</p>
            </a>
        </div>
    </div>
    <!-- end .row -->
</div>
<!-- end .container -->
<div class="mb-100">
</div>